# TF Syntax Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.14.0


In [3]:
hello  = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [8]:
print(result)

b'Hello World'


In [9]:
a = tf.constant(10)

In [10]:
b = tf. constant(20)

In [11]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [12]:
result

30

In [13]:
const = tf.constant(10)

In [14]:
fill_mat = tf.fill((4,4), 10)

In [15]:
myzeros = tf.zeros((4,4))

In [16]:
myones = tf.ones((4,4))

In [17]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [18]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [19]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [20]:
sess = tf.InteractiveSession()

In [21]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.16064662 -0.28859097  0.66847026  0.7539429 ]
 [ 0.53001076  0.33251315  0.17754717  1.3804456 ]
 [ 1.6621343  -0.02575899  0.01437763 -0.8875359 ]
 [ 1.2682588  -0.5065129  -0.35215458  0.7305719 ]]


[[0.8726909  0.4632424  0.86359715 0.16580617]
 [0.4526981  0.35181093 0.3212322  0.49524188]
 [0.18731713 0.24175656 0.17818964 0.40565896]
 [0.9106194  0.7698829  0.16514099 0.7172599 ]]




In [22]:
a = tf.constant([[1,2], [3,4]])

In [23]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [24]:
b = tf.constant([[10], [100]])

In [25]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [26]:
result = tf.matmul(a,b)

In [27]:
sess.run(result)

array([[210],
       [430]])

In [28]:
result.eval()

array([[210],
       [430]])